version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-amahh}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-amahh}
      POSTGRES_DB: ${DB_NAME:-edu-help-assign}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
