version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-amahh}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-amahh}
      POSTGRES_DB: ${DB_NAME:-edu-help-assign}
      POSTGRES_PORT: ${DB_PORT:-5438}
    ports:
      - '5438:5438'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
