import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { extractRouterConfig } from 'uploadthing/server';
import { ourFileRouter } from '@/src/app/api/uploadthing/core';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '@/src/components/providers';
import NextTopLoader from 'nextjs-toploader';
import '@uploadthing/react/styles.css';
import { Toaster } from '@/src/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function ProfileLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <div className='min-h-screen'>{children}</div>;
}
