import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { extractRouterConfig } from 'uploadthing/server';
import { ourFileRouter } from '@/src/app/api/uploadthing/core';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '@/components/providers';
import NextTopLoader from 'nextjs-toploader';
import '@uploadthing/react/styles.css';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} overflow-hidden `}
				suppressHydrationWarning={true}>
				<NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
				<NextTopLoader showSpinner={false} />
				<Providers>
					<Toaster />
					{children}
				</Providers>
			</body>
		</html>
	);
}
